# -*- coding: utf-8 -*-
"""Transport.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vUuRcX60fqWNFYpJLi2RwzP0CvFUvMYD

#Transportation system of wales
This is the coding of the Transports data set provided

Relevant libraries are imported
"""

import pandas as pd

import seaborn as sns

import os

import plotly as plt

import numpy as np

import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

"""The directory is listed."""

os.listdir()

"""**The data for "Ease of getting too and from Hospital".**"""

df=pd.read_excel("Hospital.xlsx")

df

df.shape

"""Description of the table"""

df.describe()

df.info()

"""Which categories have a very easy value of over and under 50%?"""

df.loc[df["very easy"]>50]

df.loc[df["very easy"]<50]

"""Creating a stackedbar chart to represent dataset"""

sns.set_theme(style="ticks")

#formatting the table
df.plot(kind="barh", stacked=True, color =["green", "yellow","orange", "red"],figsize=(15,15))
plt.yticks(list(range(0,34)),df["Catogory"].values)

#create label for x axis
plt.xlabel("score (%)")
#create label for y axis
plt.ylabel("category")
#legend title
plt.title("Ease of getting too and from Hospital")

"""**Age VS Ease of access to Hospital**"""

df = pd.read_excel('Age.xlsx')

df

import plotly.express as px
fig = px.scatter(df, x="category", y="Very easy")
fig.update_traces(marker_size=10)
fig.update_layout(scattermode="group")
fig.show()

"""**Data from "Overall satisfaction with the Wales Transportation system."**"""

df = pd.read_excel('Overall satisfaction.xlsx')

df

df.describe()

plt.figure(figsize=(20,15))
sns.barplot(x='Mean', y='Satisfaction', data=df.sort_values('Mean', ascending=False), color='b')
plt.title("Overall Satisfaction with state of transprotation system in Wales")
plt.xlabel("Mean Satisfaction")
plt.ylabel("Category")
plt.show()

plt.figure(figsize=(10,6))
sns.histplot(df["Mean"], bins=10, kde=True)

df_selected = df[(df["Mean"]>=5.8)& (df["Mean"]<=6.1)]
df_selected

plt.figure(figsize=(10,8))
sns.barplot(x='Mean', y='Satisfaction', data=df_selected.sort_values('Mean', ascending=False), color='b')
plt.title("Overall Satisfaction with state of transport in Wales")
plt.xlabel("Mean Satisfaction")
plt.ylabel("Category")
plt.show()

df_selected.describe()

"""**Data from "ease of getting too and from GP".**"""

df=pd.read_excel("GP.xlsx")

df

df.shape

df.describe()

#formatting the table
df.plot(kind="barh", stacked=True, color =["green", "yellow","orange", "red"], figsize=(15,15))

plt.yticks(list(range(0,34)), df["Category"].values)

#create label for x axis
plt.xlabel("score (%)")
#create label for y axis
plt.ylabel("category")
#legend title
plt.title("Ease of getting too and from GP")

"""**Feeling of safety travelling using transportation systems**"""

#loading relevant data set
df = pd.read_excel("Safety.xlsx")

df

df.describe()

df.info()

df.shape

df.describe()

#plotting data from table
f, axes = plt.subplots(2,2, figsize=(15,10))

sns.barplot(x='Very safe', y='Category', data=df, ax=axes[0,0], color='b')
sns.barplot(x='Fairly safe', y='Category', data=df, ax=axes[0,1], color='g')
sns.barplot(x='Fairly unsafe', y='Category', data=df, ax=axes[1,0], color='orange')
sns.barplot(x='Very unsafe', y='Category', data=df, ax=axes[1,1], color='r')

axes[0,0].set_title("Very safe", fontsize=14)
axes[0,1].set_title("Fairly safe", fontsize=14)
axes[1,0].set_title("Fairly unsafe", fontsize=14)
axes[1,1].set_title("Very unsafe", fontsize=14)

plt.suptitle("Feeling of safety travelling by public transport after dark", fontsize=20)
plt.tight_layout()

"""**Use of car**"""

df = pd.read_excel("Use of car.xlsx")

df

df.describe()

df.info()

#formatting the table
df.plot(kind="barh", stacked=True, color =["green", "red"], figsize=(15,15))

plt.yticks(list(range(0,19)), df["Category"].values)

#create label for x axis
plt.xlabel("score (%)")
#create label for y axis
plt.ylabel("category")
#legend title
plt.title("Use of car")

